# Main Directories
ORIG_HEART_DIR = "fitbit_data/original_data/heart/"
ORIG_PH_DIR = "fitbit_data/original_data/physical_activity/"
ORIG_SLEEP_DIR = "fitbit_data/original_data/sleep/"
ORIG_STRESS_DIR = "fitbit_data/original_data/stress/"
ORIG_O2_VAR_DIR = "fitbit_data/original_data/estimated_oxygen_variation/"

NEW_HEART_DIR = "fitbit_data/new_data/heart/"
NEW_PH_DIR = "fitbit_data/new_data/physical_activity/"
NEW_SLEEP_DIR = "fitbit_data/new_data/sleep/"
NEW_STRESS_DIR = "fitbit_data/new_data/stress/"
NEW_O2_VAR_DIR = "fitbit_data/new_data/estimated_oxygen_variation/"

# Single daily data
RHR_DIR = ORIG_HEART_DIR + "resting_heart_rate/*.json"
AZM_DIR = ORIG_PH_DIR + "active_minutes/active_zone_minutes/*.csv"
AZM_LIGHT_DIR = ORIG_PH_DIR + "active_minutes/lightly_active_minutes/*.json"
AZM_MODERATE_DIR = ORIG_PH_DIR + "active_minutes/moderately_active_minutes/*.json"
AZM_SEDENTARY_DIR = ORIG_PH_DIR + "active_minutes/sedentary_minutes/*.json"
AZM_VERY_ACTIVE_DIR = ORIG_PH_DIR + "active_minutes/very_active_minutes/*.json"
DRS_DIR = ORIG_PH_DIR + "daily_readiness/*.csv"
VO2_MAX_DIR = ORIG_PH_DIR + "demographic_vo2_max/*.json"
DRR_DIR = ORIG_SLEEP_DIR + "respiratory_rate/*.csv"
HRV_DAILY_DIR = ORIG_SLEEP_DIR + "heart_rate_variability/daily/*.csv"
HRV_HIST_DIR = ORIG_SLEEP_DIR + "heart_rate_variability/histogram/*.csv"
SLEEP_DIR = ORIG_SLEEP_DIR + "sleep/*.json"
SLEEP_SCORE_DIR = ORIG_SLEEP_DIR + "sleep/*.csv"
COMP_TEMP_DIR = ORIG_SLEEP_DIR + "temperature/computed/Computed Temperature - *.csv"
STRESS_SCORE_DIR = ORIG_STRESS_DIR + "stress_score/*.csv"
TIME_IN_HR_ZONES_DIR = ORIG_PH_DIR + "time_in_heart_rate_zones/*.json"

# Multiple daily data
O2_VAR_DIR = ORIG_O2_VAR_DIR + "*.csv"
HR_DIR = ORIG_HEART_DIR + "heart_rate/*.json"
STEPS_DIR = ORIG_PH_DIR + "steps/*.json"
DISTANCE_DIR = ORIG_PH_DIR + "distance/*.json"
ALTITUDE_DIR = ORIG_PH_DIR + "altitude/*json"
CALORIES_DIR = ORIG_PH_DIR + "calories/*.json"
HRV_DIR = ORIG_SLEEP_DIR + "heart_rate_variability/details/*.csv"
WRIST_TEMP_DIR = ORIG_SLEEP_DIR + "temperature/wrist/*.csv"

# Recorded activity and signals
EXERCISE_DIR = ORIG_PH_DIR + "exercise/*.json"
ECG_DIR = ORIG_HEART_DIR + "ecg/*.csv"
SNORE_DIR = ORIG_SLEEP_DIR + "snore/*.csv"
EDA_DIR = ORIG_STRESS_DIR + "eda/*.csv"
